-- Clean up existing role permissions and rebuild them properly

-- First, remove existing permissions to start clean
TRUNCATE role_permissions;

-- Insert default permissions for all roles and all navigation items
INSERT INTO role_permissions (role, menu_item, is_enabled) VALUES
-- Admin permissions (all enabled)
('admin', 'dashboard', true),
('admin', 'leads', true),
('admin', 'applicants', true),
('admin', 'students', true),
('admin', 'agents', true),
('admin', 'invoice', true),
('admin', 'office_expenses', true),
('admin', 'hostel_mess', true),
('admin', 'accounts', true),
('admin', 'document_management', true),
('admin', 'visa', true),
('admin', 'staff', true),
('admin', 'universities', true),
('admin', 'salary_management', true),
('admin', 'personal_expenses', true),
('admin', 'reports', true),
('admin', 'profile', false),
('admin', 'settings', true),

-- Agent permissions (limited access)
('agent', 'dashboard', true),
('agent', 'leads', false),
('agent', 'applicants', false),
('agent', 'students', true),
('agent', 'agents', false),
('agent', 'invoice', false),
('agent', 'office_expenses', false),
('agent', 'hostel_mess', false),
('agent', 'accounts', false),
('agent', 'document_management', false),
('agent', 'visa', false),
('agent', 'staff', false),
('agent', 'universities', false),
('agent', 'salary_management', false),
('agent', 'personal_expenses', false),
('agent', 'reports', false),
('agent', 'profile', true),
('agent', 'settings', false),

-- Staff permissions (moderate access)
('staff', 'dashboard', true),
('staff', 'leads', false),
('staff', 'applicants', false),
('staff', 'students', true),
('staff', 'agents', false),
('staff', 'invoice', false),
('staff', 'office_expenses', true),
('staff', 'hostel_mess', false),
('staff', 'accounts', false),
('staff', 'document_management', false),
('staff', 'visa', false),
('staff', 'staff', false),
('staff', 'universities', false),
('staff', 'salary_management', false),
('staff', 'personal_expenses', false),
('staff', 'reports', false),
('staff', 'profile', false),
('staff', 'settings', false),

-- Finance permissions (financial operations)
('finance', 'dashboard', true),
('finance', 'leads', false),
('finance', 'applicants', false),
('finance', 'students', true),
('finance', 'agents', false),
('finance', 'invoice', true),
('finance', 'office_expenses', true),
('finance', 'hostel_mess', false),
('finance', 'accounts', true),
('finance', 'document_management', false),
('finance', 'visa', false),
('finance', 'staff', false),
('finance', 'universities', false),
('finance', 'salary_management', true),
('finance', 'personal_expenses', true),
('finance', 'reports', true),
('finance', 'profile', false),
('finance', 'settings', true),

-- Hostel team permissions (hostel and accommodation)
('hostel_team', 'dashboard', true),
('hostel_team', 'leads', false),
('hostel_team', 'applicants', false),
('hostel_team', 'students', true),
('hostel_team', 'agents', false),
('hostel_team', 'invoice', false),
('hostel_team', 'office_expenses', false),
('hostel_team', 'hostel_mess', true),
('hostel_team', 'accounts', false),
('hostel_team', 'document_management', false),
('hostel_team', 'visa', false),
('hostel_team', 'staff', false),
('hostel_team', 'universities', false),
('hostel_team', 'salary_management', false),
('hostel_team', 'personal_expenses', false),
('hostel_team', 'reports', false),
('hostel_team', 'profile', false),
('hostel_team', 'settings', true);